services:
  - type: web
    name: signalr-server
    env: dotnet
    buildCommand: dotnet build
    startCommand: dotnet run --project APP2signalr.csproj
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    autoDeploy: true
    branch: main
